const CHRONICLES={
  gilded:{name:'The Gilded Consortium',legend:'Lady Aurica',color:'#c49a48',pitch:'Build wealth, recruit premium cards, and turn possessions into Glory.',start:{name:'Small Investment',effect:'gold',value:1,text:'+1 Gold. Recruit a costly card for bonus Glory.'},cards:[['Silver-Tongued Factor',3,'action','gold',2,'+2 Gold. Chain 2: +1 Gold.'],['Merchant Caravan',4,'action','gold',3,'+3 Gold.'],['Consortium Auditor',4,'champion','discount',1,'Exhaust: Your next recruit costs 1 less.',3],['Profitable Venture',5,'action','gold',4,'+4 Gold. Chain 2: +1 Glory.'],["Appraiser's Eye",5,'action','draw',1,'+2 Gold. Draw a card.'],['Master of Ledgers',6,'guard','gold',2,'Exhaust: +2 Gold.',4],['Hostile Takeover',7,'action','mixed',5,'+5 Gold and +1 Glory.'],['Golden Opportunity',6,'action','glory',3,'+3 Glory.']]},
  midnight:{name:'The Midnight Parliament',legend:'Corven',color:'#77639e',pitch:'Chain cards together, draw deeply, and turn spare Gold into Might.',start:{name:'Listening Crow',effect:'gold',value:1,text:'+1 Gold. Chain 2: Draw a card.'},cards:[['Rooftop Whisper',2,'action','gold',1,'+1 Gold. Chain 2: +1 Gold.'],['Blackwing Courier',3,'action','gold',2,'+2 Gold. Chain 3: Draw a card.'],['Parliament Informant',4,'champion','gold',1,'Exhaust: +1 Gold.',3],['Shiny Distraction',4,'action','mixed',2,'+2 Gold. Chain 3: +2 Might.'],['Gather the Flock',5,'action','draw',1,'Draw a card. Chain 2: +2 Gold.'],['Night Market Knave',5,'champion','gold',1,'Exhaust: +1 Gold.',4],['Hundred Watching Eyes',6,'action','draw',1,'+3 Gold. Draw a card.'],["Speaker's Decree",7,'action','draw',2,'Draw two cards.']]},
  hours:{name:'The Keeper of Hours',legend:'Sera Vey',color:'#4d8a8e',pitch:'Scout future draws, filter weak cards, and control enemy Champions.',start:{name:'Fleeting Insight',effect:'draw',value:0,text:'Scout, then draw a card.'},cards:[['Moment of Clarity',2,'action','gold',1,'+1 Gold. Scout your next draw.'],['Patient Observer',3,'champion','draw',0,'Exhaust: Draw, then discard.',3],['Borrowed Second',3,'action','gold',2,'+2 Gold.'],['Turn the Glass',4,'action','draw',1,'Draw a card.'],['Temporal Rebuke',4,'action','might',3,'+3 Might.'],['Curator of Moments',5,'guard','draw',0,'Exhaust: Draw, then discard.',4],['Rewrite the Hour',6,'action','draw',2,'Draw two cards.'],['The Perfect Moment',7,'action','mixed',3,'+3 Gold and +3 Might.']]},
  crimson:{name:'The Crimson Standard',legend:'Marshal Oren',color:'#a74c40',pitch:'Field Guards, recover Champions, and press the rival with Might.',start:{name:'Young Volunteer',effect:'might',value:1,text:'+1 Might.'},cards:[['Shield-Line Recruit',2,'guard','none',0,'Guard.',2],['Rallying Cry',3,'action','might',2,'+2 Might. Chain 2: +1 Might.'],['Veteran Spear',4,'champion','might',1,'Exhaust: +1 Might.',3],['Hold the Gate',4,'action','might',3,'+3 Might.'],['Banner Captain',5,'guard','might',1,'Guard. Exhaust: +1 Might.',4],['Honored Dead',5,'action','draw',1,'Draw a card and gain +1 Might.'],['Unbroken Advance',6,'action','might',5,'+5 Might.'],['The Blood-Red Banner',7,'guard','might',2,'Guard. Exhaust: +2 Might.',5]]},
  velvet:{name:'The Velvet Fox',legend:'Vessa',color:'#b06e83',pitch:'Disrupt the rival, diminish Glory, and seed their deck with Doubts.',start:{name:'Marked Coin',effect:'gold',value:1,text:'+1 Gold.'},cards:[['False Smile',2,'action','gold',1,'+1 Gold. Chain 2: +1 Might.'],['Cutpurse',3,'champion','gold',1,'Exhaust: +1 Gold.',2],['Misdirection',3,'action','gold',2,'+2 Gold.'],['Planted Evidence',4,'action','doubt',1,'+1 Gold. Give the rival a Doubt.'],['Velvet-Footed Burglar',4,'champion','might',1,'Exhaust: +1 Might.',3],['Poisoned Compliment',5,'action','steal',2,'+2 Gold. Rival loses 1 Glory.'],['House of Mirrors',5,'guard','none',0,'Guard.',4],["Vessa's Masterstroke",7,'action','doubt',3,'+3 Gold. Give the rival a Doubt.']]},
  ashen:{name:'The Ashen Reaver',legend:'Brenn Ash-Hand',color:'#b66742',pitch:'Banish weak cards, concentrate your deck, and generate relentless Might.',start:{name:'Blood Price',effect:'might',value:1,text:'+1 Might.'},cards:[['Cinder Acolyte',2,'action','might',2,'+2 Might.'],['Ruthless Forager',3,'action','gold',2,'+2 Gold.'],['Scarred Marauder',4,'champion','might',1,'Exhaust: +1 Might.',3],['Feed the Flame',4,'action','banish',2,'+2 Gold. Banish a Copper from your Rest pile.'],['Ashen Rite',5,'action','might',3,'+3 Might.'],['Bone-Crowned Seer',5,'champion','draw',0,'Exhaust: Draw a card.',4],['No Weakness',5,'action','might',4,'+4 Might if your deck is lean.'],['Reaver Chieftain',6,'guard','might',2,'Guard. Exhaust: +2 Might.',5]]}
};
const state={selected:[],market:[],marketDeck:[],turn:'player',over:false,invoked:false,chain:{},message:'',finale:null,player:null,ai:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function card(name,cost,type,suit,effect,value,text,durability=0){return{id:crypto.randomUUID(),name,cost,type,suit,effect,value,text,durability,ready:true}}
function createCard(raw,suit){return card(raw[0],raw[1],raw[2],suit,raw[3],raw[4],raw[5],raw[6]||0)}
function basic(name='Copper'){return card(name,0,'action','common','gold',name==='Copper'?1:2,`+${name==='Copper'?1:2} Gold.`)}
function doubt(){return card('Doubt',0,'burden','velvet','none',0,'No effect. A costly seed of uncertainty.')}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function makePlayer(name){const deck=[...Array(6)].map(()=>basic());state.selected.forEach(k=>{const s=CHRONICLES[k].start;deck.push(card(s.name,0,'action',k,s.effect,s.value,s.text))});return{name,draw:shuffle(deck),discard:[],hand:[],played:[],champions:[],gold:0,might:0,glory:0,discount:0}}
function draw(p,n=1){for(let i=0;i<n;i++){if(!p.draw.length){p.draw=shuffle(p.discard.splice(0));}if(p.draw.length)p.hand.push(p.draw.pop())}}
function setupChoices(){const box=$('#chronicleChoices');Object.entries(CHRONICLES).forEach(([k,c])=>{const d=document.createElement('div');d.className='choice';d.dataset.key=k;d.innerHTML=`<span class="check">◆</span><span class="eyebrow">${c.legend}</span><h3>${c.name}</h3><p>${c.pitch}</p>`;d.onclick=()=>toggleChoice(k,d);box.append(d)})}
function toggleChoice(k,el){if(state.selected.includes(k)){state.selected=state.selected.filter(x=>x!==k);el.classList.remove('selected')}else if(state.selected.length<4){state.selected.push(k);el.classList.add('selected')}$('#selectionHelp').textContent=`${state.selected.length} of 4 Chronicles chosen.`;$('#startGame').disabled=state.selected.length!==4}
function start(){state.over=false;state.turn='player';state.invoked=false;state.chain={};state.finale=null;state.player=makePlayer('You');state.ai=makePlayer('The Rival');state.marketDeck=[];state.selected.forEach(k=>CHRONICLES[k].cards.forEach(r=>{state.marketDeck.push(createCard(r,k));state.marketDeck.push(createCard(r,k))}));['Open Market','Traveling Broker','Call in a Favor','Public Bounty'].forEach((n,i)=>{for(let q=0;q<3;q++)state.marketDeck.push(card(n,2+i,'action','common',i===3?'might':'gold',i===3?3:2,i===3?'+3 Might.':'+2 Gold.'))});shuffle(state.marketDeck);state.market=[];refill();draw(state.player,5);draw(state.ai,5);$('#setup').classList.add('hidden');$('#game').classList.remove('hidden');log('Your story begins. Play a card from your hand.');render()}
function refill(){while(state.market.length<5&&state.marketDeck.length)state.market.push(state.marketDeck.pop())}
function apply(p,c,isAI=false){state.chain[c.suit]=(state.chain[c.suit]||0)+1;let v=c.value||0;if(c.effect==='gold')p.gold+=v;if(c.effect==='might')p.might+=v;if(c.effect==='glory')p.glory+=v;if(c.effect==='mixed'){p.gold+=v;p.might+=Math.min(3,v)}if(c.effect==='draw')draw(p,v||1);if(c.effect==='discount')p.discount+=v;if(c.effect==='steal'){p.gold+=v;const foe=isAI?state.player:state.ai;foe.glory=Math.max(0,foe.glory-1)}if(c.effect==='doubt'){p.gold+=v;(isAI?state.player:state.ai).discard.push(doubt())}if(c.effect==='banish'){p.gold+=v;const ix=p.discard.findIndex(x=>x.name==='Copper');if(ix>=0)p.discard.splice(ix,1)}if(c.suit==='midnight'&&state.chain[c.suit]>=2&&c.name.includes('Whisper'))p.gold++;if(c.suit==='midnight'&&state.chain[c.suit]>=3&&c.name.includes('Courier'))draw(p);if(c.suit==='crimson'&&state.chain[c.suit]>=2&&c.name==='Rallying Cry')p.might++;if(c.suit==='velvet'&&state.chain[c.suit]>=2&&c.name==='False Smile')p.might++;if(c.suit==='gilded'&&state.chain[c.suit]>=2&&c.name==='Silver-Tongued Factor')p.gold++;if(c.name==='Profitable Venture'&&state.chain[c.suit]>=2)p.glory++;if(c.name==='Hostile Takeover')p.glory++;if(c.name==='Hundred Watching Eyes')p.gold+=3;if(c.name==='Honored Dead')p.might++;if(c.name==='No Weakness'&&p.draw.length+p.discard.length<13)p.might+=2}
function playCard(i,isAI=false){const p=isAI?state.ai:state.player;if(state.over||(!isAI&&state.turn!=='player'))return;const c=p.hand.splice(i,1)[0];if(!c)return;if(c.type==='champion'||c.type==='guard')p.champions.push(c);else{apply(p,c,isAI);p.played.push(c)}if(!isAI){log(`You played ${c.name}.`);render()}}
function activateChampion(i,isAI=false){const p=isAI?state.ai:state.player,c=p.champions[i];if(!c||!c.ready)return;c.ready=false;apply(p,c,isAI);if(!isAI){log(`${c.name} answers your call.`);render()}}
function buy(i,isAI=false){const p=isAI?state.ai:state.player,c=state.market[i];if(!c)return false;const cost=Math.max(0,c.cost-p.discount);if(p.gold<cost)return false;p.gold-=cost;p.discount=0;p.discard.push(c);state.market.splice(i,1);refill();if(!isAI){log(`You recruited ${c.name}.`);render()}return true}
function attackChampion(i){const c=state.ai.champions[i];if(!c)return;const guards=state.ai.champions.filter(x=>x.type==='guard');if(guards.length&&c.type!=='guard'){log('A Guard protects that Champion.');return}if(state.player.might<c.durability){log(`You need ${c.durability} Might to defeat ${c.name}.`);return}state.player.might-=c.durability;state.ai.discard.push(...state.ai.champions.splice(i,1));log(`You defeated ${c.name}.`);render()}
function invoke(k,isAI=false){const p=isAI?state.ai:state.player,foe=isAI?state.player:state.ai;if(state.invoked)return false;let paid=false;if(k==='gilded'&&p.played.length){const c=p.played.sort((a,b)=>b.cost-a.cost)[0],ix=p.played.indexOf(c);p.played.splice(ix,1);p.glory+=Math.ceil(c.cost/2);paid=true}else if(k==='midnight'&&p.gold>=3){p.might+=Math.ceil(p.gold/2);p.gold=0;paid=true}else if(k==='hours'&&p.gold>=4&&foe.champions.length){p.gold-=4;foe.discard.push(foe.champions.shift());paid=true}else if(k==='crimson'&&p.might>=2){p.might-=2;const ix=p.discard.findIndex(x=>x.type==='champion'||x.type==='guard');if(ix>=0)p.hand.push(...p.discard.splice(ix,1));else p.might+=1;paid=true}else if(k==='velvet'&&p.gold>=3){p.gold-=3;if(state.legends[k]===(isAI?'ai':'player'))foe.discard.push(doubt());else foe.glory=Math.max(0,foe.glory-1);paid=true}else if(k==='ashen'&&p.might>=2&&p.played.length){p.might-=2;p.played.shift();draw(p);paid=true}if(paid){state.legends[k]=state.legends[k]===(isAI?'ai':'player')?null:(isAI?'ai':'player');state.invoked=true;if(!isAI){log(`You invoked ${CHRONICLES[k].legend}.`);render()}}return paid}
function endTurn(){if(state.turn!=='player'||state.over)return;state.player.glory+=state.player.might;state.player.might=0;cleanup(state.player);if(checkWin('player'))return;state.turn='ai';render();log('The Rival considers the Crossroads…');setTimeout(aiTurn,650)}
function cleanup(p){p.discard.push(...p.played.splice(0),...p.hand.splice(0));p.gold=0;p.might=0;p.discount=0;p.champions.forEach(c=>c.ready=true);draw(p,5)}
function aiTurn(){if(state.over)return;state.invoked=false;state.chain={};while(state.ai.hand.length)playCard(0,true);state.ai.champions.forEach((_,i)=>activateChampion(i,true));let bought=true;while(bought){bought=false;const options=state.market.map((c,i)=>({c,i})).filter(x=>x.c.cost<=state.ai.gold+state.ai.discount).sort((a,b)=>b.c.cost-a.c.cost);if(options.length){buy(options[0].i,true);bought=true}}const invokable=shuffle([...state.selected]);for(const k of invokable)if(invoke(k,true))break;while(state.ai.might>0&&state.player.champions.length){let ix=state.player.champions.findIndex(c=>c.type==='guard'&&c.durability<=state.ai.might);if(ix<0)ix=state.player.champions.findIndex(c=>c.durability<=state.ai.might);if(ix<0)break;const c=state.player.champions[ix];state.ai.might-=c.durability;state.player.discard.push(...state.player.champions.splice(ix,1))}state.ai.glory+=state.ai.might;state.ai.might=0;cleanup(state.ai);if(checkWin('ai'))return;state.turn='player';state.invoked=false;state.chain={};log('Your turn. The Crossroads await.');render()}
function checkWin(who){const p=who==='player'?state.player:state.ai;const allegiance=state.selected.every(k=>state.legends[k]===who);if(allegiance){finish(who,`${p.name} secured the Allegiance of all four Legends.`);return true}if(p.glory>=40){const foe=who==='player'?state.ai:state.player;if(state.finale&&state.finale!==who){if(p.glory>=foe.glory){finish(who,`${p.name} answered the Glory challenge and finished with ${p.glory} Glory.`);return true}}else state.finale=who}if(state.finale&&state.finale!==who){const challenger=state.finale==='player'?state.player:state.ai;if(p.glory<challenger.glory){finish(state.finale,`${challenger.name} reached ${challenger.glory} Glory and survived the final response.`);return true}state.finale=null}return false}
function finish(who,text){state.over=true;$('#resultTitle').textContent=who==='player'?'Your sacrifice becomes legend':'The Rival claims the tale';$('#resultText').textContent=text;$('#resultDialog').showModal()}
function log(t){state.message=t;$('#log').textContent=t}
function renderCard(c,mode,i){const affordable=mode==='market'&&state.player.gold+state.player.discount<c.cost;const d=document.createElement('article');d.className=`card ${affordable?'unaffordable':''}`;d.style.borderTopColor=CHRONICLES[c.suit]?.color||'#b99b61';d.innerHTML=`<span class="suit">${CHRONICLES[c.suit]?.name||'Common Purse'}</span>${mode==='market'?`<span class="cost">${c.cost}</span>`:''}<h3>${c.name}</h3><span class="type">${c.type}${c.durability?` · ${c.durability} durability`:''}</span><p class="effect">${c.text}</p>${c.type==='guard'?'<span class="durability">◆ Guard</span>':''}`;d.onclick=()=>mode==='market'?buy(i):playCard(i);return d}
function panel(p,isAI){const champs=p.champions.map((c,i)=>`<span class="mini-champion ${c.type==='guard'?'guard':''}" data-i="${i}" title="${c.text}">${c.name} · ${c.durability}◆</span>`).join('');return `<strong>${p.name}</strong><div class="champions">${champs||'<span style="color:#777">No Champions</span>'}</div><div class="player-stats"><span>Deck <b>${p.draw.length}</b></span><span>Rest <b>${p.discard.length}</b></span>${isAI?`<span>Glory <b>${p.glory}</b></span>`:''}</div>`}
function render(){if(!state.player)return;$('#market').replaceChildren(...state.market.map((c,i)=>renderCard(c,'market',i)));const hand=$('#hand');hand.replaceChildren(...state.player.hand.map((c,i)=>renderCard(c,'hand',i)));hand.classList.toggle('empty',!state.player.hand.length);if(!state.player.hand.length)hand.textContent='Your hand is empty. Recruit, invoke a Legend, or end your turn.';$('#playerPanel').innerHTML=panel(state.player,false);$('#aiPanel').innerHTML=panel(state.ai,true);$$('#aiPanel .mini-champion').forEach(el=>el.onclick=()=>attackChampion(+el.dataset.i));$$('#playerPanel .mini-champion').forEach(el=>el.onclick=()=>activateChampion(+el.dataset.i));$('#gold').textContent=state.player.gold;$('#might').textContent=state.player.might;$('#glory').textContent=state.player.glory;$('#turnBanner').textContent=state.turn==='player'?'Your turn':'Rival’s turn';$('#endTurn').disabled=state.turn!=='player';$('#playAll').disabled=state.turn!=='player'||!state.player.hand.length;const legends=$('#legends');legends.innerHTML='';state.selected.forEach(k=>{const c=CHRONICLES[k],owner=state.legends[k];const d=document.createElement('article');d.className=`legend ${owner||''}`;d.innerHTML=`<h3>${c.legend}</h3><p>${legendText(k)}</p><button ${state.turn!=='player'||state.invoked?'disabled':''}>Invoke</button>`;d.querySelector('button').onclick=()=>{if(!invoke(k))log('You cannot pay this Legend’s price right now.')};legends.append(d)})}
function legendText(k){return{gilded:'Sacrifice a played card: gain half its cost as Glory.',midnight:'Pay all Gold (minimum 3): gain half as Might.',hours:'Pay 4 Gold: defeat a rival Champion.',crimson:'Pay 2 Might: recover a Champion.',velvet:'Pay 3 Gold: diminish Glory or create Doubt.',ashen:'Pay 2 Might and sacrifice a played card: draw.'}[k]}
setupChoices();state.legends={};$('#startGame').onclick=start;$('#playAll').onclick=()=>{while(state.player.hand.length)playCard(0);render()};$('#endTurn').onclick=endTurn;$('#newGame').onclick=()=>location.reload();$('#resultRestart').onclick=()=>location.reload();$('#rulesButton').onclick=()=>$('#rulesDialog').showModal();$('#rulesDialog .dialog-close').onclick=()=>$('#rulesDialog').close();

// Optional browser-agent controls. They invoke the same actions as the visible board.
if(document.modelContext?.registerTool){
  const register=(tool)=>Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});
  register({name:'start_story_game',title:'Start story game',description:'Start a new Stories of Sacrifice match with exactly four Chronicle IDs.',inputSchema:{type:'object',properties:{chronicles:{type:'array',items:{type:'string',enum:Object.keys(CHRONICLES)},minItems:4,maxItems:4,uniqueItems:true}},required:['chronicles'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({chronicles}){if(!Array.isArray(chronicles)||chronicles.length!==4||new Set(chronicles).size!==4||chronicles.some(k=>!CHRONICLES[k]))throw new Error('Choose four unique valid Chronicles.');state.selected=[...chronicles];start();return{status:'started',chronicles:state.selected,turn:state.turn}}});
  register({name:'play_all_cards',title:'Play all cards',description:'Play every card currently in the human player’s hand.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){if(!state.player||state.turn!=='player'||state.over)throw new Error('Cards cannot be played right now.');const count=state.player.hand.length;while(state.player.hand.length)playCard(0);render();return{status:'played',count,gold:state.player.gold,might:state.player.might,glory:state.player.glory}}});
}
